require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - '0*/**/*'
    - '1*/**/*'
    - '2*/**/*'
    - '3*/**/*'
    - '4*/**/*'
    - '5*/**/*'
    - '6*/**/*'
    - '7*/**/*'
    - '8*/**/*'
    - '9*/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 45

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'Rakefile'

Minitest/MultipleAssertions:
  Max: 10
